/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: OraProtoBuf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "olr/OraProtoBuf.pb-c.h"
void   open_log_replicator__pb__value__init
                     (OpenLogReplicator__Pb__Value         *message)
{
  static const OpenLogReplicator__Pb__Value init_value = OPEN_LOG_REPLICATOR__PB__VALUE__INIT;
  *message = init_value;
}
size_t open_log_replicator__pb__value__get_packed_size
                     (const OpenLogReplicator__Pb__Value *message)
{
  assert(message->base.descriptor == &open_log_replicator__pb__value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_log_replicator__pb__value__pack
                     (const OpenLogReplicator__Pb__Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_log_replicator__pb__value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_log_replicator__pb__value__pack_to_buffer
                     (const OpenLogReplicator__Pb__Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_log_replicator__pb__value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenLogReplicator__Pb__Value *
       open_log_replicator__pb__value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenLogReplicator__Pb__Value *)
     protobuf_c_message_unpack (&open_log_replicator__pb__value__descriptor,
                                allocator, len, data);
}
void   open_log_replicator__pb__value__free_unpacked
                     (OpenLogReplicator__Pb__Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_log_replicator__pb__value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   open_log_replicator__pb__column__init
                     (OpenLogReplicator__Pb__Column         *message)
{
  static const OpenLogReplicator__Pb__Column init_value = OPEN_LOG_REPLICATOR__PB__COLUMN__INIT;
  *message = init_value;
}
size_t open_log_replicator__pb__column__get_packed_size
                     (const OpenLogReplicator__Pb__Column *message)
{
  assert(message->base.descriptor == &open_log_replicator__pb__column__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_log_replicator__pb__column__pack
                     (const OpenLogReplicator__Pb__Column *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_log_replicator__pb__column__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_log_replicator__pb__column__pack_to_buffer
                     (const OpenLogReplicator__Pb__Column *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_log_replicator__pb__column__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenLogReplicator__Pb__Column *
       open_log_replicator__pb__column__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenLogReplicator__Pb__Column *)
     protobuf_c_message_unpack (&open_log_replicator__pb__column__descriptor,
                                allocator, len, data);
}
void   open_log_replicator__pb__column__free_unpacked
                     (OpenLogReplicator__Pb__Column *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_log_replicator__pb__column__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   open_log_replicator__pb__schema__init
                     (OpenLogReplicator__Pb__Schema         *message)
{
  static const OpenLogReplicator__Pb__Schema init_value = OPEN_LOG_REPLICATOR__PB__SCHEMA__INIT;
  *message = init_value;
}
size_t open_log_replicator__pb__schema__get_packed_size
                     (const OpenLogReplicator__Pb__Schema *message)
{
  assert(message->base.descriptor == &open_log_replicator__pb__schema__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_log_replicator__pb__schema__pack
                     (const OpenLogReplicator__Pb__Schema *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_log_replicator__pb__schema__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_log_replicator__pb__schema__pack_to_buffer
                     (const OpenLogReplicator__Pb__Schema *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_log_replicator__pb__schema__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenLogReplicator__Pb__Schema *
       open_log_replicator__pb__schema__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenLogReplicator__Pb__Schema *)
     protobuf_c_message_unpack (&open_log_replicator__pb__schema__descriptor,
                                allocator, len, data);
}
void   open_log_replicator__pb__schema__free_unpacked
                     (OpenLogReplicator__Pb__Schema *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_log_replicator__pb__schema__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   open_log_replicator__pb__payload__init
                     (OpenLogReplicator__Pb__Payload         *message)
{
  static const OpenLogReplicator__Pb__Payload init_value = OPEN_LOG_REPLICATOR__PB__PAYLOAD__INIT;
  *message = init_value;
}
size_t open_log_replicator__pb__payload__get_packed_size
                     (const OpenLogReplicator__Pb__Payload *message)
{
  assert(message->base.descriptor == &open_log_replicator__pb__payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_log_replicator__pb__payload__pack
                     (const OpenLogReplicator__Pb__Payload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_log_replicator__pb__payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_log_replicator__pb__payload__pack_to_buffer
                     (const OpenLogReplicator__Pb__Payload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_log_replicator__pb__payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenLogReplicator__Pb__Payload *
       open_log_replicator__pb__payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenLogReplicator__Pb__Payload *)
     protobuf_c_message_unpack (&open_log_replicator__pb__payload__descriptor,
                                allocator, len, data);
}
void   open_log_replicator__pb__payload__free_unpacked
                     (OpenLogReplicator__Pb__Payload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_log_replicator__pb__payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   open_log_replicator__pb__schema_request__init
                     (OpenLogReplicator__Pb__SchemaRequest         *message)
{
  static const OpenLogReplicator__Pb__SchemaRequest init_value = OPEN_LOG_REPLICATOR__PB__SCHEMA_REQUEST__INIT;
  *message = init_value;
}
size_t open_log_replicator__pb__schema_request__get_packed_size
                     (const OpenLogReplicator__Pb__SchemaRequest *message)
{
  assert(message->base.descriptor == &open_log_replicator__pb__schema_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_log_replicator__pb__schema_request__pack
                     (const OpenLogReplicator__Pb__SchemaRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_log_replicator__pb__schema_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_log_replicator__pb__schema_request__pack_to_buffer
                     (const OpenLogReplicator__Pb__SchemaRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_log_replicator__pb__schema_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenLogReplicator__Pb__SchemaRequest *
       open_log_replicator__pb__schema_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenLogReplicator__Pb__SchemaRequest *)
     protobuf_c_message_unpack (&open_log_replicator__pb__schema_request__descriptor,
                                allocator, len, data);
}
void   open_log_replicator__pb__schema_request__free_unpacked
                     (OpenLogReplicator__Pb__SchemaRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_log_replicator__pb__schema_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   open_log_replicator__pb__redo_request__init
                     (OpenLogReplicator__Pb__RedoRequest         *message)
{
  static const OpenLogReplicator__Pb__RedoRequest init_value = OPEN_LOG_REPLICATOR__PB__REDO_REQUEST__INIT;
  *message = init_value;
}
size_t open_log_replicator__pb__redo_request__get_packed_size
                     (const OpenLogReplicator__Pb__RedoRequest *message)
{
  assert(message->base.descriptor == &open_log_replicator__pb__redo_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_log_replicator__pb__redo_request__pack
                     (const OpenLogReplicator__Pb__RedoRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_log_replicator__pb__redo_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_log_replicator__pb__redo_request__pack_to_buffer
                     (const OpenLogReplicator__Pb__RedoRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_log_replicator__pb__redo_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenLogReplicator__Pb__RedoRequest *
       open_log_replicator__pb__redo_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenLogReplicator__Pb__RedoRequest *)
     protobuf_c_message_unpack (&open_log_replicator__pb__redo_request__descriptor,
                                allocator, len, data);
}
void   open_log_replicator__pb__redo_request__free_unpacked
                     (OpenLogReplicator__Pb__RedoRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_log_replicator__pb__redo_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   open_log_replicator__pb__redo_response__attributes_entry__init
                     (OpenLogReplicator__Pb__RedoResponse__AttributesEntry         *message)
{
  static const OpenLogReplicator__Pb__RedoResponse__AttributesEntry init_value = OPEN_LOG_REPLICATOR__PB__REDO_RESPONSE__ATTRIBUTES_ENTRY__INIT;
  *message = init_value;
}
void   open_log_replicator__pb__redo_response__init
                     (OpenLogReplicator__Pb__RedoResponse         *message)
{
  static const OpenLogReplicator__Pb__RedoResponse init_value = OPEN_LOG_REPLICATOR__PB__REDO_RESPONSE__INIT;
  *message = init_value;
}
size_t open_log_replicator__pb__redo_response__get_packed_size
                     (const OpenLogReplicator__Pb__RedoResponse *message)
{
  assert(message->base.descriptor == &open_log_replicator__pb__redo_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_log_replicator__pb__redo_response__pack
                     (const OpenLogReplicator__Pb__RedoResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_log_replicator__pb__redo_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_log_replicator__pb__redo_response__pack_to_buffer
                     (const OpenLogReplicator__Pb__RedoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_log_replicator__pb__redo_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenLogReplicator__Pb__RedoResponse *
       open_log_replicator__pb__redo_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenLogReplicator__Pb__RedoResponse *)
     protobuf_c_message_unpack (&open_log_replicator__pb__redo_response__descriptor,
                                allocator, len, data);
}
void   open_log_replicator__pb__redo_response__free_unpacked
                     (OpenLogReplicator__Pb__RedoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_log_replicator__pb__redo_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor open_log_replicator__pb__value__field_descriptors[6] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Value, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_int",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    offsetof(OpenLogReplicator__Pb__Value, datum_case),
    offsetof(OpenLogReplicator__Pb__Value, value_int),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_float",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(OpenLogReplicator__Pb__Value, datum_case),
    offsetof(OpenLogReplicator__Pb__Value, value_float),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_double",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(OpenLogReplicator__Pb__Value, datum_case),
    offsetof(OpenLogReplicator__Pb__Value, value_double),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_string",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(OpenLogReplicator__Pb__Value, datum_case),
    offsetof(OpenLogReplicator__Pb__Value, value_string),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_bytes",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(OpenLogReplicator__Pb__Value, datum_case),
    offsetof(OpenLogReplicator__Pb__Value, value_bytes),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_log_replicator__pb__value__field_indices_by_name[] = {
  0,   /* field[0] = name */
  5,   /* field[5] = value_bytes */
  3,   /* field[3] = value_double */
  2,   /* field[2] = value_float */
  1,   /* field[1] = value_int */
  4,   /* field[4] = value_string */
};
static const ProtobufCIntRange open_log_replicator__pb__value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor open_log_replicator__pb__value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.Value",
  "Value",
  "OpenLogReplicator__Pb__Value",
  "OpenLogReplicator.pb",
  sizeof(OpenLogReplicator__Pb__Value),
  6,
  open_log_replicator__pb__value__field_descriptors,
  open_log_replicator__pb__value__field_indices_by_name,
  1,  open_log_replicator__pb__value__number_ranges,
  (ProtobufCMessageInit) open_log_replicator__pb__value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor open_log_replicator__pb__column__field_descriptors[6] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Column, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Column, type),
    &open_log_replicator__pb__column_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Column, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "precision",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Column, precision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Column, scale),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nullable",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Column, nullable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_log_replicator__pb__column__field_indices_by_name[] = {
  2,   /* field[2] = length */
  0,   /* field[0] = name */
  5,   /* field[5] = nullable */
  3,   /* field[3] = precision */
  4,   /* field[4] = scale */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange open_log_replicator__pb__column__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor open_log_replicator__pb__column__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.Column",
  "Column",
  "OpenLogReplicator__Pb__Column",
  "OpenLogReplicator.pb",
  sizeof(OpenLogReplicator__Pb__Column),
  6,
  open_log_replicator__pb__column__field_descriptors,
  open_log_replicator__pb__column__field_indices_by_name,
  1,  open_log_replicator__pb__column__number_ranges,
  (ProtobufCMessageInit) open_log_replicator__pb__column__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor open_log_replicator__pb__schema__field_descriptors[6] =
{
  {
    "owner",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Schema, owner),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Schema, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "obj",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Schema, obj),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tm",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(OpenLogReplicator__Pb__Schema, tm_val_case),
    offsetof(OpenLogReplicator__Pb__Schema, tm),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tms",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(OpenLogReplicator__Pb__Schema, tm_val_case),
    offsetof(OpenLogReplicator__Pb__Schema, tms),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "column",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenLogReplicator__Pb__Schema, n_column),
    offsetof(OpenLogReplicator__Pb__Schema, column),
    &open_log_replicator__pb__column__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_log_replicator__pb__schema__field_indices_by_name[] = {
  5,   /* field[5] = column */
  1,   /* field[1] = name */
  2,   /* field[2] = obj */
  0,   /* field[0] = owner */
  3,   /* field[3] = tm */
  4,   /* field[4] = tms */
};
static const ProtobufCIntRange open_log_replicator__pb__schema__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor open_log_replicator__pb__schema__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.Schema",
  "Schema",
  "OpenLogReplicator__Pb__Schema",
  "OpenLogReplicator.pb",
  sizeof(OpenLogReplicator__Pb__Schema),
  6,
  open_log_replicator__pb__schema__field_descriptors,
  open_log_replicator__pb__schema__field_indices_by_name,
  1,  open_log_replicator__pb__schema__number_ranges,
  (ProtobufCMessageInit) open_log_replicator__pb__schema__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor open_log_replicator__pb__payload__field_descriptors[10] =
{
  {
    "op",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Payload, op),
    &open_log_replicator__pb__op__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schema",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Payload, schema),
    &open_log_replicator__pb__schema__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Payload, rid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "before",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenLogReplicator__Pb__Payload, n_before),
    offsetof(OpenLogReplicator__Pb__Payload, before),
    &open_log_replicator__pb__value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "after",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenLogReplicator__Pb__Payload, n_after),
    offsetof(OpenLogReplicator__Pb__Payload, after),
    &open_log_replicator__pb__value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ddl",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Payload, ddl),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Payload, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Payload, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "redo",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Payload, redo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__Payload, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_log_replicator__pb__payload__field_indices_by_name[] = {
  4,   /* field[4] = after */
  3,   /* field[3] = before */
  5,   /* field[5] = ddl */
  9,   /* field[9] = num */
  7,   /* field[7] = offset */
  0,   /* field[0] = op */
  8,   /* field[8] = redo */
  2,   /* field[2] = rid */
  1,   /* field[1] = schema */
  6,   /* field[6] = seq */
};
static const ProtobufCIntRange open_log_replicator__pb__payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor open_log_replicator__pb__payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.Payload",
  "Payload",
  "OpenLogReplicator__Pb__Payload",
  "OpenLogReplicator.pb",
  sizeof(OpenLogReplicator__Pb__Payload),
  10,
  open_log_replicator__pb__payload__field_descriptors,
  open_log_replicator__pb__payload__field_indices_by_name,
  1,  open_log_replicator__pb__payload__number_ranges,
  (ProtobufCMessageInit) open_log_replicator__pb__payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor open_log_replicator__pb__schema_request__field_descriptors[2] =
{
  {
    "mask",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__SchemaRequest, mask),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filter",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__SchemaRequest, filter),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_log_replicator__pb__schema_request__field_indices_by_name[] = {
  1,   /* field[1] = filter */
  0,   /* field[0] = mask */
};
static const ProtobufCIntRange open_log_replicator__pb__schema_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor open_log_replicator__pb__schema_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.SchemaRequest",
  "SchemaRequest",
  "OpenLogReplicator__Pb__SchemaRequest",
  "OpenLogReplicator.pb",
  sizeof(OpenLogReplicator__Pb__SchemaRequest),
  2,
  open_log_replicator__pb__schema_request__field_descriptors,
  open_log_replicator__pb__schema_request__field_indices_by_name,
  1,  open_log_replicator__pb__schema_request__number_ranges,
  (ProtobufCMessageInit) open_log_replicator__pb__schema_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor open_log_replicator__pb__redo_request__field_descriptors[9] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoRequest, code),
    &open_log_replicator__pb__request_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "database_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoRequest, database_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scn",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(OpenLogReplicator__Pb__RedoRequest, tm_val_case),
    offsetof(OpenLogReplicator__Pb__RedoRequest, scn),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tms",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(OpenLogReplicator__Pb__RedoRequest, tm_val_case),
    offsetof(OpenLogReplicator__Pb__RedoRequest, tms),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tm_rel",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    offsetof(OpenLogReplicator__Pb__RedoRequest, tm_val_case),
    offsetof(OpenLogReplicator__Pb__RedoRequest, tm_rel),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoRequest, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schema",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenLogReplicator__Pb__RedoRequest, n_schema),
    offsetof(OpenLogReplicator__Pb__RedoRequest, schema),
    &open_log_replicator__pb__schema_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_scn",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoRequest, c_scn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_idx",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoRequest, c_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_log_replicator__pb__redo_request__field_indices_by_name[] = {
  8,   /* field[8] = c_idx */
  7,   /* field[7] = c_scn */
  0,   /* field[0] = code */
  1,   /* field[1] = database_name */
  6,   /* field[6] = schema */
  2,   /* field[2] = scn */
  5,   /* field[5] = seq */
  4,   /* field[4] = tm_rel */
  3,   /* field[3] = tms */
};
static const ProtobufCIntRange open_log_replicator__pb__redo_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor open_log_replicator__pb__redo_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.RedoRequest",
  "RedoRequest",
  "OpenLogReplicator__Pb__RedoRequest",
  "OpenLogReplicator.pb",
  sizeof(OpenLogReplicator__Pb__RedoRequest),
  9,
  open_log_replicator__pb__redo_request__field_descriptors,
  open_log_replicator__pb__redo_request__field_indices_by_name,
  1,  open_log_replicator__pb__redo_request__number_ranges,
  (ProtobufCMessageInit) open_log_replicator__pb__redo_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor open_log_replicator__pb__redo_response__attributes_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoResponse__AttributesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoResponse__AttributesEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_log_replicator__pb__redo_response__attributes_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange open_log_replicator__pb__redo_response__attributes_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor open_log_replicator__pb__redo_response__attributes_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.RedoResponse.AttributesEntry",
  "AttributesEntry",
  "OpenLogReplicator__Pb__RedoResponse__AttributesEntry",
  "OpenLogReplicator.pb",
  sizeof(OpenLogReplicator__Pb__RedoResponse__AttributesEntry),
  2,
  open_log_replicator__pb__redo_response__attributes_entry__field_descriptors,
  open_log_replicator__pb__redo_response__attributes_entry__field_indices_by_name,
  1,  open_log_replicator__pb__redo_response__attributes_entry__number_ranges,
  (ProtobufCMessageInit) open_log_replicator__pb__redo_response__attributes_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor open_log_replicator__pb__redo_response__field_descriptors[12] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoResponse, code),
    &open_log_replicator__pb__response_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scn",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(OpenLogReplicator__Pb__RedoResponse, scn_val_case),
    offsetof(OpenLogReplicator__Pb__RedoResponse, scn),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scns",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(OpenLogReplicator__Pb__RedoResponse, scn_val_case),
    offsetof(OpenLogReplicator__Pb__RedoResponse, scns),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tm",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(OpenLogReplicator__Pb__RedoResponse, tm_val_case),
    offsetof(OpenLogReplicator__Pb__RedoResponse, tm),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tms",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(OpenLogReplicator__Pb__RedoResponse, tm_val_case),
    offsetof(OpenLogReplicator__Pb__RedoResponse, tms),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xid",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(OpenLogReplicator__Pb__RedoResponse, xid_val_case),
    offsetof(OpenLogReplicator__Pb__RedoResponse, xid),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xidn",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(OpenLogReplicator__Pb__RedoResponse, xid_val_case),
    offsetof(OpenLogReplicator__Pb__RedoResponse, xidn),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "db",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoResponse, db),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenLogReplicator__Pb__RedoResponse, n_payload),
    offsetof(OpenLogReplicator__Pb__RedoResponse, payload),
    &open_log_replicator__pb__payload__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_scn",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoResponse, c_scn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_idx",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(OpenLogReplicator__Pb__RedoResponse, c_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpenLogReplicator__Pb__RedoResponse, n_attributes),
    offsetof(OpenLogReplicator__Pb__RedoResponse, attributes),
    &open_log_replicator__pb__redo_response__attributes_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_log_replicator__pb__redo_response__field_indices_by_name[] = {
  11,   /* field[11] = attributes */
  10,   /* field[10] = c_idx */
  9,   /* field[9] = c_scn */
  0,   /* field[0] = code */
  7,   /* field[7] = db */
  8,   /* field[8] = payload */
  1,   /* field[1] = scn */
  2,   /* field[2] = scns */
  3,   /* field[3] = tm */
  4,   /* field[4] = tms */
  5,   /* field[5] = xid */
  6,   /* field[6] = xidn */
};
static const ProtobufCIntRange open_log_replicator__pb__redo_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor open_log_replicator__pb__redo_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.RedoResponse",
  "RedoResponse",
  "OpenLogReplicator__Pb__RedoResponse",
  "OpenLogReplicator.pb",
  sizeof(OpenLogReplicator__Pb__RedoResponse),
  12,
  open_log_replicator__pb__redo_response__field_descriptors,
  open_log_replicator__pb__redo_response__field_indices_by_name,
  1,  open_log_replicator__pb__redo_response__number_ranges,
  (ProtobufCMessageInit) open_log_replicator__pb__redo_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue open_log_replicator__pb__op__enum_values_by_number[7] =
{
  { "BEGIN", "OPEN_LOG_REPLICATOR__PB__OP__BEGIN", 0 },
  { "COMMIT", "OPEN_LOG_REPLICATOR__PB__OP__COMMIT", 1 },
  { "INSERT", "OPEN_LOG_REPLICATOR__PB__OP__INSERT", 2 },
  { "UPDATE", "OPEN_LOG_REPLICATOR__PB__OP__UPDATE", 3 },
  { "DELETE", "OPEN_LOG_REPLICATOR__PB__OP__DELETE", 4 },
  { "DDL", "OPEN_LOG_REPLICATOR__PB__OP__DDL", 5 },
  { "CHKPT", "OPEN_LOG_REPLICATOR__PB__OP__CHKPT", 6 },
};
static const ProtobufCIntRange open_log_replicator__pb__op__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex open_log_replicator__pb__op__enum_values_by_name[7] =
{
  { "BEGIN", 0 },
  { "CHKPT", 6 },
  { "COMMIT", 1 },
  { "DDL", 5 },
  { "DELETE", 4 },
  { "INSERT", 2 },
  { "UPDATE", 3 },
};
const ProtobufCEnumDescriptor open_log_replicator__pb__op__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.Op",
  "Op",
  "OpenLogReplicator__Pb__Op",
  "OpenLogReplicator.pb",
  7,
  open_log_replicator__pb__op__enum_values_by_number,
  7,
  open_log_replicator__pb__op__enum_values_by_name,
  1,
  open_log_replicator__pb__op__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue open_log_replicator__pb__column_type__enum_values_by_number[18] =
{
  { "UNKNOWN", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__UNKNOWN", 0 },
  { "VARCHAR2", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__VARCHAR2", 1 },
  { "NUMBER", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__NUMBER", 2 },
  { "LONG", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__LONG", 3 },
  { "DATE", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__DATE", 4 },
  { "RAW", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__RAW", 5 },
  { "LONG_RAW", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__LONG_RAW", 6 },
  { "CHAR", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__CHAR", 7 },
  { "BINARY_FLOAT", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__BINARY_FLOAT", 8 },
  { "BINARY_DOUBLE", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__BINARY_DOUBLE", 9 },
  { "CLOB", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__CLOB", 10 },
  { "BLOB", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__BLOB", 11 },
  { "TIMESTAMP", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__TIMESTAMP", 12 },
  { "TIMESTAMP_WITH_TZ", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__TIMESTAMP_WITH_TZ", 13 },
  { "INTERVAL_YEAR_TO_MONTH", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__INTERVAL_YEAR_TO_MONTH", 14 },
  { "INTERVAL_DAY_TO_SECOND", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__INTERVAL_DAY_TO_SECOND", 15 },
  { "UROWID", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__UROWID", 16 },
  { "TIMESTAMP_WITH_LOCAL_TZ", "OPEN_LOG_REPLICATOR__PB__COLUMN_TYPE__TIMESTAMP_WITH_LOCAL_TZ", 17 },
};
static const ProtobufCIntRange open_log_replicator__pb__column_type__value_ranges[] = {
{0, 0},{0, 18}
};
static const ProtobufCEnumValueIndex open_log_replicator__pb__column_type__enum_values_by_name[18] =
{
  { "BINARY_DOUBLE", 9 },
  { "BINARY_FLOAT", 8 },
  { "BLOB", 11 },
  { "CHAR", 7 },
  { "CLOB", 10 },
  { "DATE", 4 },
  { "INTERVAL_DAY_TO_SECOND", 15 },
  { "INTERVAL_YEAR_TO_MONTH", 14 },
  { "LONG", 3 },
  { "LONG_RAW", 6 },
  { "NUMBER", 2 },
  { "RAW", 5 },
  { "TIMESTAMP", 12 },
  { "TIMESTAMP_WITH_LOCAL_TZ", 17 },
  { "TIMESTAMP_WITH_TZ", 13 },
  { "UNKNOWN", 0 },
  { "UROWID", 16 },
  { "VARCHAR2", 1 },
};
const ProtobufCEnumDescriptor open_log_replicator__pb__column_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.ColumnType",
  "ColumnType",
  "OpenLogReplicator__Pb__ColumnType",
  "OpenLogReplicator.pb",
  18,
  open_log_replicator__pb__column_type__enum_values_by_number,
  18,
  open_log_replicator__pb__column_type__enum_values_by_name,
  1,
  open_log_replicator__pb__column_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue open_log_replicator__pb__request_code__enum_values_by_number[4] =
{
  { "INFO", "OPEN_LOG_REPLICATOR__PB__REQUEST_CODE__INFO", 0 },
  { "START", "OPEN_LOG_REPLICATOR__PB__REQUEST_CODE__START", 1 },
  { "CONTINUE", "OPEN_LOG_REPLICATOR__PB__REQUEST_CODE__CONTINUE", 2 },
  { "CONFIRM", "OPEN_LOG_REPLICATOR__PB__REQUEST_CODE__CONFIRM", 3 },
};
static const ProtobufCIntRange open_log_replicator__pb__request_code__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex open_log_replicator__pb__request_code__enum_values_by_name[4] =
{
  { "CONFIRM", 3 },
  { "CONTINUE", 2 },
  { "INFO", 0 },
  { "START", 1 },
};
const ProtobufCEnumDescriptor open_log_replicator__pb__request_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.RequestCode",
  "RequestCode",
  "OpenLogReplicator__Pb__RequestCode",
  "OpenLogReplicator.pb",
  4,
  open_log_replicator__pb__request_code__enum_values_by_number,
  4,
  open_log_replicator__pb__request_code__enum_values_by_name,
  1,
  open_log_replicator__pb__request_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue open_log_replicator__pb__response_code__enum_values_by_number[8] =
{
  { "READY", "OPEN_LOG_REPLICATOR__PB__RESPONSE_CODE__READY", 0 },
  { "FAILED_START", "OPEN_LOG_REPLICATOR__PB__RESPONSE_CODE__FAILED_START", 1 },
  { "STARTING", "OPEN_LOG_REPLICATOR__PB__RESPONSE_CODE__STARTING", 2 },
  { "ALREADY_STARTED", "OPEN_LOG_REPLICATOR__PB__RESPONSE_CODE__ALREADY_STARTED", 3 },
  { "REPLICATE", "OPEN_LOG_REPLICATOR__PB__RESPONSE_CODE__REPLICATE", 4 },
  { "PAYLOAD", "OPEN_LOG_REPLICATOR__PB__RESPONSE_CODE__PAYLOAD", 5 },
  { "INVALID_DATABASE", "OPEN_LOG_REPLICATOR__PB__RESPONSE_CODE__INVALID_DATABASE", 6 },
  { "INVALID_COMMAND", "OPEN_LOG_REPLICATOR__PB__RESPONSE_CODE__INVALID_COMMAND", 7 },
};
static const ProtobufCIntRange open_log_replicator__pb__response_code__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex open_log_replicator__pb__response_code__enum_values_by_name[8] =
{
  { "ALREADY_STARTED", 3 },
  { "FAILED_START", 1 },
  { "INVALID_COMMAND", 7 },
  { "INVALID_DATABASE", 6 },
  { "PAYLOAD", 5 },
  { "READY", 0 },
  { "REPLICATE", 4 },
  { "STARTING", 2 },
};
const ProtobufCEnumDescriptor open_log_replicator__pb__response_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.ResponseCode",
  "ResponseCode",
  "OpenLogReplicator__Pb__ResponseCode",
  "OpenLogReplicator.pb",
  8,
  open_log_replicator__pb__response_code__enum_values_by_number,
  8,
  open_log_replicator__pb__response_code__enum_values_by_name,
  1,
  open_log_replicator__pb__response_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCMethodDescriptor open_log_replicator__pb__open_log_replicator__method_descriptors[1] =
{
  { "Redo", &open_log_replicator__pb__redo_request__descriptor, &open_log_replicator__pb__redo_response__descriptor },
};
const unsigned open_log_replicator__pb__open_log_replicator__method_indices_by_name[] = {
  0         /* Redo */
};
const ProtobufCServiceDescriptor open_log_replicator__pb__open_log_replicator__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "OpenLogReplicator.pb.OpenLogReplicator",
  "OpenLogReplicator",
  "OpenLogReplicator__Pb__OpenLogReplicator",
  "OpenLogReplicator.pb",
  1,
  open_log_replicator__pb__open_log_replicator__method_descriptors,
  open_log_replicator__pb__open_log_replicator__method_indices_by_name
};
void open_log_replicator__pb__open_log_replicator__redo(ProtobufCService *service,
                                                        const OpenLogReplicator__Pb__RedoRequest *input,
                                                        OpenLogReplicator__Pb__RedoResponse_Closure closure,
                                                        void *closure_data)
{
  assert(service->descriptor == &open_log_replicator__pb__open_log_replicator__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void open_log_replicator__pb__open_log_replicator__init (OpenLogReplicator__Pb__OpenLogReplicator_Service *service,
                                                         OpenLogReplicator__Pb__OpenLogReplicator_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &open_log_replicator__pb__open_log_replicator__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
