/*
 * format_converter.h
 *
 * Header file for the SynchDB format converter module
 *
 * This module provides structures and functions for processing
 * database change events in Debezium (DBZ) format and converting
 * them to a format suitable for SynchDB.
 *
 * Key components:
 * - Structures for representing DDL (Data Definition Language) events
 * - Structures for representing DML (Data Manipulation Language) events
 * - Functions for processing and converting DBZ change events
 *
 * Copyright (c) Hornetlabs Technology, Inc.
 * 
 */

#ifndef SYNCHDB_FORMAT_CONVERTER_H_
#define SYNCHDB_FORMAT_CONVERTER_H_

#include "utils/hsearch.h"
#include "nodes/pg_list.h"
#include "replication_agent.h"
#include "synchdb.h"

/* constants */
#define RULEFILE_DATATYPE_TRANSFORM 1
#define RULEFILE_OBJECTNAME_TRANSFORM 2
#define RULEFILE_EXPRESSION_TRANSFORM 3

/* structure to hold possible time representations in DBZ engine */
typedef enum _timeRep
{
	TIME_UNDEF = 0,
	TIME_DATE,				/* number of days since epoch */
	TIME_TIME,				/* number of milliseconds since epoch */
	TIME_MICROTIME,			/* number of microseconds since midnight */
	TIME_NANOTIME,			/* number of nanoseconds since midnight */
	TIME_TIMESTAMP,			/* number of milliseconds since epoch */
	TIME_MICROTIMESTAMP,	/* number of microseconds since epoch */
	TIME_NANOTIMESTAMP,		/* number of nanoseconds since epoch */
	TIME_ZONEDTIMESTAMP,	/* string representation of timestamp with timezone */
	TIME_MICRODURATION,	/* duration expressed in microseconds */
	DATA_VARIABLE_SCALE,	/* indication if scale is variable (for oracle) */
	DATA_GEOMETRY,			/* indication of geometry data */
	DATA_ENUM,				/* indication of enum data */
} TimeRep;

/*
 * DbzType
 *
 * enum that represents how foreign systems (dbz or olr) could represent
 * a data value
 */
typedef enum _DbzType
{
	/* DBZ types */
	DBZTYPE_UNDEF = 0,
	DBZTYPE_FLOAT32,
	DBZTYPE_FLOAT64,
	DBZTYPE_FLOAT,
	DBZTYPE_DOUBLE,
	DBZTYPE_BYTES,
	DBZTYPE_INT8,
	DBZTYPE_INT16,
	DBZTYPE_INT32,
	DBZTYPE_INT64,
	DBZTYPE_STRUCT,
	DBZTYPE_STRING,

	/* OLR types */
	OLRTYPE_NUMBER,
	OLRTYPE_STRING
} DbzType;

/* Structure to represent a column in a DDL event */
typedef struct dbz_ddl_column
{
	char * name;
	int length;
	bool optional;
	int position;
	char * typeName;
	char * enumValues;
	char * charsetName;
	bool autoIncremented;
	char * defaultValueExpression;
	int scale;
} DBZ_DDL_COLUMN;

/* another alias to the same DDL COLUMN struct for clarity */
typedef DBZ_DDL_COLUMN OLR_DDL_COLUMN;

/* Structure to represent a DDL event */
typedef struct dbz_ddl
{
	char * id;
	char * type;
	char * subtype;
	char * primaryKeyColumnNames;
	char * constraintName;
	List * columns;		/* list of DBZ_DDL_COLUMN */
	unsigned long long dbz_ts_ms;	/* time(ms) when this DDL is processed by DBZ */
	unsigned long long src_ts_ms;	/* time(ms) when this DDL is generated by source database */
} DBZ_DDL;

/* another alias to the same DDL struct for clarity */
typedef DBZ_DDL OLR_DDL;

typedef struct
{
	char name[NAMEDATALEN];
	Oid oid;
	int position;
	int typemod;
	bool ispk;
	char typcategory;
	bool typispreferred;
	char typname[NAMEDATALEN];
} NameOidEntry;

typedef struct
{
	char name[NAMEDATALEN];
	int jsonpos;
	DbzType dbztype;
	TimeRep timerep;
	int scale;
} NameJsonposEntry;

/* Structure to represent a column value in a DML event */
typedef struct dbz_dml_column_value
{
	char * name;	/* name of the column field */
	char * remoteColumnName;	/* original column name from remote server */
	char * value;	/* expressed as string as taken from json */
	Oid datatype;	/* data type Oid as defined by PostgreSQL */
	int position;	/* position of this column value, start from 1 */
	int scale;		/* location of decimal point - decimal type only */
	int timerep;	/* how dbz represents time related fields */
	int typemod;	/* extra data type modifier */
	bool ispk;		/* indicate if this column is a primary key*/
	DbzType dbztype;	/* data literal type as defined by dbz */
	char typcategory;	/* type category defined by pg */
	bool typispreferred;	/* wether type category is preferred by pg */
	char * typname;		/* the name of the data type */
} DBZ_DML_COLUMN_VALUE;

/* Structure to represent a DML event */
typedef struct dbz_dml
{
	char op;
	char * schema;
	char * table;
	char * remoteObjectId;		/* db.schema.table or db.table on remote side */
	char * mappedObjectId;		/* schema.table, or just table on PG side */
	Oid tableoid;
	int natts;					/* number of columns of this pg table */
	List * columnValuesBefore;	/* list of DBZ_DML_COLUMN_VALUE */
	List * columnValuesAfter;	/* list of DBZ_DML_COLUMN_VALUE */
	unsigned long long dbz_ts_ms;	/* time(ms) when this DML is processed by DBZ */
	unsigned long long src_ts_ms;	/* time(ms) when this DML is generated by source database */
} DBZ_DML;

/* another alias to the same DML struct for clarity */
typedef DBZ_DML OLR_DML;

/* dml cache structure */
typedef struct dataCacheKey
{
	char schema[SYNCHDB_CONNINFO_DB_NAME_SIZE];
	char table[SYNCHDB_CONNINFO_DB_NAME_SIZE];
} DataCacheKey;
typedef struct dataCacheEntry
{
	DataCacheKey key;
	TupleDesc tupdesc;
	Oid tableoid;
	HTAB * typeidhash;
	HTAB * namejsonposhash;
	int natts;
} DataCacheEntry;

typedef struct datatypeHashKey
{
	char extTypeName[SYNCHDB_DATATYPE_NAME_SIZE];
	bool autoIncremented;
} DatatypeHashKey;

typedef struct datatypeHashEntry
{
	DatatypeHashKey key;
	char pgsqlTypeName[SYNCHDB_DATATYPE_NAME_SIZE];
	int pgsqlTypeLength;
} DatatypeHashEntry;

typedef struct objMapHashKey
{
	char extObjName[SYNCHDB_OBJ_NAME_SIZE];
	char extObjType[SYNCHDB_OBJ_TYPE_SIZE];
} ObjMapHashKey;

typedef struct objMapHashEntry
{
	ObjMapHashKey key;
	char pgsqlObjName[SYNCHDB_OBJ_NAME_SIZE];
} ObjMapHashEntry;

typedef struct transformExpressionHashKey
{
	char extObjName[SYNCHDB_OBJ_NAME_SIZE];
} TransformExpressionHashKey;

typedef struct transformExpressionHashEntry
{
	TransformExpressionHashKey key;
	char pgsqlTransExpress[SYNCHDB_TRANSFORM_EXPRESSION_SIZE];
} TransformExpressionHashEntry;

/* Function prototypes */
int fc_processDBZChangeEvent(const char * event, SynchdbStatistics * myBatchStats,
		bool schemasync, const char * name, bool isfirst, bool islast);
ConnectorType fc_get_connector_type(const char * connector);
void fc_initFormatConverter(ConnectorType connectorType);
void fc_deinitFormatConverter(ConnectorType connectorType);
bool fc_load_rules(ConnectorType connectorType, const char * rulefile);
bool fc_load_objmap(const char * name, ConnectorType connectorType);
char * escapeSingleQuote(const char * in, bool addquote);
int fc_processOLRChangeEvent(const char * event, SynchdbStatistics * myBatchStats,
		const char * name, bool * sendconfirm, bool isfirst, bool islast);

#endif /* SYNCHDB_FORMAT_CONVERTER_H_ */
