/*-------------------------------------------------------------------------
 *
 * ora_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef ORA_KWLIST_D_H
#define ORA_KWLIST_D_H

#include "common/kwlookup.h"

static const char OraScanKeywords_kw_string[] =
	"abort\0"
	"absent\0"
	"absolute\0"
	"access\0"
	"accessible\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"array\0"
	"as\0"
	"asc\0"
	"asensitive\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"atomic\0"
	"attach\0"
	"attribute\0"
	"authid\0"
	"authorization\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"binary_double\0"
	"binary_double_infinity\0"
	"binary_double_nan\0"
	"binary_float\0"
	"binary_float_infinity\0"
	"binary_float_nan\0"
	"bit\0"
	"boolean\0"
	"both\0"
	"breadth\0"
	"by\0"
	"byte\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compile\0"
	"compression\0"
	"concurrently\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"date\0"
	"day\0"
	"deallocate\0"
	"debug\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"depends\0"
	"depth\0"
	"desc\0"
	"detach\0"
	"deterministic\0"
	"dictionary\0"
	"disable\0"
	"discard\0"
	"distinct\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"each\0"
	"editionable\0"
	"else\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"end\0"
	"enum\0"
	"escape\0"
	"event\0"
	"except\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"explain\0"
	"expression\0"
	"extend\0"
	"extension\0"
	"external\0"
	"false\0"
	"family\0"
	"fetch\0"
	"filter\0"
	"finalize\0"
	"first\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"format\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"hash\0"
	"having\0"
	"header\0"
	"hold\0"
	"hour\0"
	"identity\0"
	"if\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"indent\0"
	"index\0"
	"indexes\0"
	"infinite\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invoker\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"ivysql\0"
	"join\0"
	"json\0"
	"json_array\0"
	"json_arrayagg\0"
	"json_object\0"
	"json_objectagg\0"
	"keep\0"
	"key\0"
	"keys\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"level\0"
	"like\0"
	"limit\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"logged\0"
	"long\0"
	"loop\0"
	"mapping\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxvalue\0"
	"merge\0"
	"metadata\0"
	"method\0"
	"minute\0"
	"minvalue\0"
	"mode\0"
	"modify\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"nan\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"new\0"
	"next\0"
	"nfc\0"
	"nfd\0"
	"nfkc\0"
	"nfkd\0"
	"no\0"
	"nocache\0"
	"nocopy\0"
	"nocycle\0"
	"noextend\0"
	"nokeep\0"
	"nomaxvalue\0"
	"nominvalue\0"
	"none\0"
	"noneditionable\0"
	"noorder\0"
	"normalize\0"
	"normalized\0"
	"noscale\0"
	"noshard\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"number\0"
	"numeric\0"
	"nvl\0"
	"nvl2\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"on\0"
	"only\0"
	"operator\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"package\0"
	"parallel\0"
	"parallel_enable\0"
	"parameter\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"passing\0"
	"password\0"
	"pgextract\0"
	"pipelined\0"
	"placing\0"
	"plans\0"
	"policy\0"
	"polymorphic\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"program\0"
	"publication\0"
	"quote\0"
	"range\0"
	"raw\0"
	"read\0"
	"real\0"
	"reassign\0"
	"recheck\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"reindex\0"
	"relative\0"
	"release\0"
	"relies_on\0"
	"rename\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"restart\0"
	"restrict\0"
	"result_cache\0"
	"return\0"
	"returning\0"
	"returns\0"
	"reuse\0"
	"revoke\0"
	"right\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"routine\0"
	"routines\0"
	"row\0"
	"rows\0"
	"rowtype\0"
	"rule\0"
	"savepoint\0"
	"scalar\0"
	"scale\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"settings\0"
	"shard\0"
	"share\0"
	"sharing\0"
	"show\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"sql\0"
	"sql_macro\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"strip\0"
	"subscription\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysdate\0"
	"sysid\0"
	"system\0"
	"system_user\0"
	"systimestamp\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"text\0"
	"then\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"uescape\0"
	"unbounded\0"
	"uncommitted\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlogged\0"
	"until\0"
	"update\0"
	"updatexml\0"
	"user\0"
	"userenv\0"
	"using\0"
	"using_nls_comp\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"varchar2\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"volatile\0"
	"when\0"
	"where\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"year\0"
	"yes\0"
	"zone";

static const uint16 OraScanKeywords_kw_offsets[] = {
	0,
	6,
	13,
	22,
	29,
	40,
	47,
	51,
	57,
	63,
	73,
	77,
	82,
	88,
	95,
	103,
	111,
	115,
	119,
	125,
	128,
	132,
	143,
	153,
	164,
	175,
	178,
	185,
	192,
	202,
	209,
	223,
	232,
	239,
	245,
	253,
	260,
	267,
	281,
	304,
	322,
	335,
	357,
	374,
	378,
	386,
	391,
	399,
	402,
	407,
	413,
	418,
	425,
	433,
	442,
	447,
	452,
	460,
	466,
	471,
	481,
	497,
	503,
	514,
	520,
	526,
	534,
	543,
	551,
	561,
	568,
	576,
	584,
	593,
	600,
	610,
	618,
	630,
	643,
	657,
	666,
	677,
	688,
	700,
	708,
	717,
	728,
	733,
	738,
	745,
	751,
	755,
	760,
	768,
	784,
	797,
	810,
	825,
	838,
	856,
	869,
	876,
	882,
	887,
	896,
	901,
	905,
	916,
	922,
	926,
	934,
	942,
	949,
	957,
	966,
	977,
	986,
	994,
	1001,
	1011,
	1022,
	1030,
	1036,
	1041,
	1048,
	1062,
	1073,
	1081,
	1089,
	1098,
	1101,
	1110,
	1117,
	1124,
	1129,
	1134,
	1146,
	1151,
	1158,
	1167,
	1177,
	1181,
	1186,
	1193,
	1199,
	1206,
	1214,
	1224,
	1234,
	1242,
	1249,
	1257,
	1268,
	1275,
	1285,
	1294,
	1300,
	1307,
	1313,
	1320,
	1329,
	1335,
	1341,
	1351,
	1355,
	1361,
	1369,
	1376,
	1384,
	1391,
	1396,
	1401,
	1410,
	1420,
	1430,
	1437,
	1443,
	1451,
	1460,
	1466,
	1475,
	1482,
	1490,
	1495,
	1502,
	1509,
	1514,
	1519,
	1528,
	1531,
	1537,
	1547,
	1557,
	1566,
	1573,
	1576,
	1584,
	1594,
	1604,
	1611,
	1617,
	1625,
	1634,
	1642,
	1651,
	1661,
	1668,
	1674,
	1680,
	1686,
	1698,
	1705,
	1713,
	1717,
	1725,
	1735,
	1744,
	1749,
	1757,
	1760,
	1767,
	1777,
	1784,
	1789,
	1794,
	1805,
	1819,
	1831,
	1846,
	1851,
	1855,
	1860,
	1866,
	1875,
	1881,
	1886,
	1894,
	1902,
	1912,
	1918,
	1923,
	1929,
	1934,
	1940,
	1947,
	1952,
	1958,
	1968,
	1983,
	1992,
	1997,
	2004,
	2011,
	2016,
	2021,
	2029,
	2035,
	2043,
	2056,
	2065,
	2071,
	2080,
	2087,
	2094,
	2103,
	2108,
	2115,
	2121,
	2126,
	2131,
	2137,
	2141,
	2150,
	2158,
	2164,
	2168,
	2173,
	2177,
	2181,
	2186,
	2191,
	2194,
	2202,
	2209,
	2217,
	2226,
	2233,
	2244,
	2255,
	2260,
	2275,
	2283,
	2293,
	2304,
	2312,
	2320,
	2324,
	2332,
	2339,
	2347,
	2354,
	2359,
	2366,
	2372,
	2379,
	2387,
	2391,
	2396,
	2403,
	2406,
	2410,
	2417,
	2422,
	2426,
	2429,
	2434,
	2443,
	2450,
	2458,
	2461,
	2467,
	2478,
	2485,
	2489,
	2495,
	2500,
	2509,
	2517,
	2528,
	2534,
	2540,
	2548,
	2557,
	2573,
	2583,
	2590,
	2598,
	2608,
	2616,
	2625,
	2635,
	2645,
	2653,
	2659,
	2666,
	2678,
	2687,
	2697,
	2707,
	2715,
	2724,
	2733,
	2741,
	2747,
	2758,
	2769,
	2779,
	2790,
	2798,
	2810,
	2816,
	2822,
	2826,
	2831,
	2836,
	2845,
	2853,
	2863,
	2867,
	2878,
	2890,
	2898,
	2906,
	2915,
	2923,
	2933,
	2940,
	2951,
	2959,
	2967,
	2973,
	2981,
	2990,
	3003,
	3010,
	3020,
	3028,
	3034,
	3041,
	3047,
	3052,
	3061,
	3068,
	3076,
	3085,
	3089,
	3094,
	3102,
	3107,
	3117,
	3124,
	3130,
	3137,
	3145,
	3152,
	3159,
	3166,
	3175,
	3182,
	3191,
	3201,
	3214,
	3221,
	3229,
	3242,
	3246,
	3252,
	3257,
	3266,
	3272,
	3278,
	3286,
	3291,
	3299,
	3306,
	3311,
	3320,
	3329,
	3334,
	3338,
	3348,
	3355,
	3366,
	3372,
	3382,
	3393,
	3399,
	3406,
	3414,
	3421,
	3428,
	3434,
	3447,
	3457,
	3465,
	3475,
	3483,
	3489,
	3496,
	3508,
	3521,
	3527,
	3534,
	3546,
	3557,
	3562,
	3571,
	3581,
	3586,
	3591,
	3596,
	3601,
	3611,
	3614,
	3623,
	3635,
	3645,
	3651,
	3659,
	3664,
	3669,
	3678,
	3686,
	3691,
	3697,
	3705,
	3715,
	3727,
	3739,
	3745,
	3752,
	3760,
	3769,
	3778,
	3784,
	3791,
	3801,
	3806,
	3814,
	3820,
	3835,
	3842,
	3848,
	3857,
	3867,
	3873,
	3880,
	3888,
	3897,
	3906,
	3914,
	3922,
	3930,
	3935,
	3941,
	3950,
	3955,
	3961,
	3972,
	3979,
	3984,
	3991,
	3999,
	4004,
	4012,
	4018,
	4022,
	4036,
	4046,
	4057,
	4067,
	4077,
	4091,
	4100,
	4106,
	4114,
	4127,
	4136,
	4141,
	4145,
};

#define ORASCANKEYWORDS_NUM_KEYWORDS 530

static int
OraScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1061] = {
		-564,  32767, -539,  -451,  32767, 32767, 32767, 37,
		63,    -652,  332,   236,   32767, 801,   156,   32767,
		32767, -94,   379,   15,    0,     0,     32767, 32767,
		318,   32767, 75,    32767, -158,  71,    32767, 217,
		-63,   32767, 118,   255,   32767, 0,     494,   32767,
		32767, 181,   239,   287,   32767, 32767, 131,   -70,
		32767, 141,   32767, 32767, 32767, 32767, 341,   -420,
		32767, 712,   272,   32767, 427,   258,   32767, 32767,
		14,    32767, -510,  2,     32767, 267,   32767, 32767,
		321,   324,   133,   432,   80,    517,   32767, 32767,
		0,     421,   32767, 237,   32767, 524,   32767, 123,
		0,     32767, 32767, 9,     513,   -182,  32767, 24,
		8,     32767, 221,   228,   156,   798,   -399,  32767,
		-67,   -300,  304,   -248,  50,    51,    32767, -10,
		32767, 32767, 32767, 32767, 772,   652,   583,   32767,
		92,    231,   32767, -11,   32767, -16,   32767, 449,
		409,   783,   -311,  0,     -263,  505,   -186,  331,
		317,   0,     240,   0,     0,     655,   32767, 0,
		-135,  0,     6,     32767, 32767, 32767, 32767, -70,
		0,     32767, 157,   -973,  32767, 132,   -411,  223,
		301,   97,    32767, 0,     32767, 140,   46,    5,
		32767, -131,  32767, 407,   297,   183,   32767, 0,
		32767, 32767, -339,  -404,  402,   -756,  449,   603,
		-529,  32767, 0,     0,     336,   -79,   32767, 564,
		32767, 32767, 106,   32767, 32767, 220,   32767, 312,
		32767, 32767, 32767, 608,   136,   261,   320,   32767,
		-399,  32767, -352,  32767, 499,   84,    -543,  225,
		480,   120,   32767, 32767, 32767, -131,  32767, -846,
		653,   32767, 32767, 0,     32767, 32767, 241,   32767,
		32767, 32767, 0,     -508,  538,   0,     32767, 32767,
		0,     32767, 32767, 0,     32767, 70,    32767, 361,
		32767, 94,    423,   431,   32767, 32767, 0,     32767,
		0,     0,     853,   0,     72,    0,     -196,  708,
		-89,   279,   -149,  856,   32767, 32767, 99,    32767,
		32767, 0,     450,   32767, 79,    183,   298,   32767,
		32767, 0,     32767, 32767, 441,   67,    358,   419,
		85,    185,   32767, 189,   26,    132,   32767, 184,
		-288,  258,   270,   32767, 32767, 32767, 32767, 32767,
		32767, 0,     32767, 32767, 32767, 32767, 337,   981,
		32767, 748,   251,   905,   32767, 449,   340,   32767,
		32767, 32767, 244,   -32,   -115,  0,     0,     140,
		246,   0,     32767, 525,   32767, 32767, 0,     612,
		32767, -283,  32767, 0,     32767, 32767, 32767, -39,
		32767, 0,     257,   129,   32767, -85,   0,     0,
		32767, 32767, 32767, 724,   180,   -184,  377,   32767,
		32767, -96,   68,    32767, 32767, 32767, 318,   32767,
		378,   123,   209,   746,   653,   266,   32767, 32767,
		32767, 32767, 32767, -302,  32767, 0,     718,   32767,
		0,     0,     32767, 396,   315,   32767, 32767, 126,
		753,   318,   32767, 32767, 32767, 352,   367,   32767,
		17,    444,   81,    32767, 32767, 32767, 548,   -512,
		519,   0,     -182,  366,   32767, 327,   476,   447,
		440,   237,   32767, 32767, 980,   168,   272,   32767,
		32767, 32767, 32767, 32767, -868,  32767, 243,   0,
		32767, 32767, -91,   456,   32767, 32767, -284,  32767,
		86,    32767, -70,   -683,  266,   87,    489,   32767,
		43,    32767, 9,     668,   414,   0,     32767, 11,
		0,     152,   32767, 32767, -195,  32767, -169,  355,
		32767, 32767, 321,   32767, 0,     170,   0,     22,
		115,   0,     32767, 0,     64,    32767, 247,   0,
		32767, 450,   -101,  252,   32767, 32767, 32767, 7,
		32767, 0,     32767, 0,     32767, 32767, -24,   32767,
		-431,  7,     -72,   470,   274,   32767, 32767, 129,
		208,   372,   73,    0,     1323,  32767, 32767, 201,
		2,     -67,   32767, 83,    -87,   391,   107,   446,
		58,    -446,  270,   0,     32767, 31,    32767, 0,
		-455,  251,   93,    213,   0,     32767, 32767, 292,
		323,   -262,  32767, 32767, 32767, 32767, 49,    32767,
		32767, 414,   32767, 0,     821,   32767, 286,   502,
		32767, 116,   -375,  103,   32767, 0,     32767, 32767,
		32767, 32767, -133,  32767, 32767, 32767, 37,    435,
		32767, 32767, 194,   -762,  -37,   225,   32767, -306,
		32767, 77,    32767, 123,   -15,   32767, 32767, 498,
		-492,  698,   32767, 32767, 32767, 526,   311,   62,
		-18,   32767, 292,   2,     32767, 0,     310,   669,
		-334,  141,   32767, 207,   32767, 401,   32767, 0,
		-254,  32767, 32767, 0,     281,   32767, 0,     32767,
		84,    399,   -397,  0,     32767, -44,   0,     0,
		183,   -81,   32767, 0,     32767, 866,   -350,  32767,
		32767, 334,   32767, 32767, 296,   0,     -468,  446,
		0,     330,   25,    32767, 32767, 32767, 28,    93,
		32767, 32767, 32767, -415,  32767, 32767, 827,   -414,
		-85,   -176,  32767, 32767, 0,     0,     32767, 0,
		175,   398,   333,   102,   0,     32767, 0,     282,
		63,    0,     0,     32767, 0,     93,    0,     0,
		0,     269,   -289,  -10,   -155,  801,   317,   289,
		514,   0,     32767, 550,   417,   0,     20,    306,
		32767, 32767, 32767, 0,     32767, 32767, 32767, 515,
		-717,  0,     32767, 32767, 0,     -902,  32767, 94,
		419,   -326,  32767, 526,   -77,   32767, -81,   295,
		273,   570,   0,     -367,  283,   513,   206,   -124,
		0,     394,   32767, 21,    395,   0,     448,   32767,
		-66,   32767, 47,    32767, 32767, 433,   981,   0,
		32767, 515,   32767, 0,     138,   253,   -206,  32767,
		32767, 212,   -738,  0,     32767, 32767, 32767, 32767,
		32767, 32767, 32767, 510,   75,    275,   32767, 108,
		497,   474,   32767, 788,   32767, 508,   100,   0,
		32767, 32767, -226,  32767, 0,     309,   0,     175,
		220,   0,     32767, -289,  -814,  0,     32767, 32767,
		0,     501,   32767, 357,   0,     200,   32767, 0,
		32767, 72,    483,   498,   0,     0,     32767, 32767,
		118,   0,     32767, 147,   245,   812,   0,     32767,
		-106,  -392,  -600,  32767, 0,     32767, -400,  32767,
		32767, 32767, 32767, 332,   0,     -171,  32767, 284,
		32767, 32767, -258,  -164,  32767, 32767, 0,     32767,
		145,   -442,  411,   249,   32767, 324,   0,     32767,
		53,    703,   369,   32767, 32767, 382,   32767, 272,
		27,    65,    279,   32767, 0,     293,   -279,  0,
		92,    386,   32767, 769,   32767, 214,   612,   -50,
		32767, 26,    32767, 336,   32767, 32767, 61,    32767,
		32767, -307,  -34,   32767, 280,   210,   32767, 32767,
		-228,  363,   32767, 32767, 512,   32767, 240,   32767,
		32767, 297,   32767, 79,    -115,  88,    -316,  32767,
		-661,  336,   0,     0,     32767, 935,   859,   32767,
		-782,  32767, 32767, 96,    0,     126,   0,     32767,
		32767, 0,     368,   314,   0,     32767, 32767, 32767,
		32767, 46,    0,     0,     383,   32767, 90,    32767,
		0,     32767, 32767, 477,   525,   290,   1039,  0,
		94,    32767, 86,    32767, 158,   -140,  -160,  0,
		0,     0,     -412,  32767, 32767, 32767, 222,   178,
		32767, -188,  561,   0,     0,     30,    0,     458,
		32767, 70,    32767, -175,  811,   32767, 0,     0,
		32767, 32767, 32767, 247,   32767, 0,     338,   0,
		1389,  427,   328,   32767, 0,     0,     505,   32767,
		32767, 215,   0,     32767, 165,   0,     230,   118,
		32767, 32767, 310,   141,   32767, 110,   -370,  32767,
		32767, 0,     339,   478,   260,   32767, 181,   238,
		193,   690,   243,   373,   32767, 32767, 424,   32767,
		32767, 0,     0,     32767, 0,     23,    0,     0,
		385,   32767, 354,   150,   0,     32767, 0,     32767,
		32767, 171,   32767, 566,   1025,  -137,  0,     114,
		32767, 386,   467,   -98,   91,    174,   32767, 318,
		246,   32767, 49,    32767, 32767
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 2;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 127 + c;
	}
	return h[a % 1061] + h[b % 1061];
}

const ScanKeywordList OraScanKeywords = {
	OraScanKeywords_kw_string,
	OraScanKeywords_kw_offsets,
	OraScanKeywords_hash_func,
	ORASCANKEYWORDS_NUM_KEYWORDS,
	22
};

#endif							/* ORA_KWLIST_D_H */
