{
 "title": "Java Virtual Machine",
 "description": "This comprehensive Java Virtual Machine monitoring dashboard is the result of many years efforts learning about monitoring and instrumenting Java applications for observability (among other things).\r\n\r\nYou'll note some interesting things above and beyond the standard metrics which are Garbage Collection throughput, memory pools, and some nice graphs allowing for analysis of GC, thread states, and memory pools and bio buffer pool.\r\n\r\nYou'll even find an overview and use of this dashboard on my YouTube channel. https://youtu.be/27Yc3gdeuQ0?si=zXXFy26k7iplBRrN",
 "time": { "from": "2025-07-07T13:51:42.460Z", "to": "2025-07-08T01:51:42.460Z" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jmx_exporter_build_info,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(jmx_exporter_build_info{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(jmx_exporter_build_info{namespace=~\"$namespace\",job=~\"$job\"},app)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(jmx_exporter_build_info{namespace=~\"$namespace\",job=\"$job\",app=~\"$app\"},pod)"
    }
   },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_availableprocessors{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_freephysicalmemorysize{instance=~\"$instance\"} / java_lang_operatingsystem_totalphysicalmemorysize{instance=~\"$instance\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(java_lang_operatingsystem_totalphysicalmemorysize{instance=~\"$instance\"} - java_lang_operatingsystem_freephysicalmemorysize{instance=~\"$instance\"}) / java_lang_operatingsystem_totalphysicalmemorysize{instance=~\"$instance\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\",job=~\"$job\",instance=~\"$instance\"})*100) / sum(jvm_memory_max_bytes{area=\"heap\",job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}"
    },
    { "expr": "jvm_runtime_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Max. File Descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_processcpuload{instance=~\"$instance\"}",
     "legendFormat": "JVM Process - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "java_lang_operatingsystem_systemcpuload{instance=~\"$instance\"}",
     "legendFormat": "Overall System - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Thread CPU/User Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(java_lang_operatingsystem_processcputime{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU time - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "increase(java_lang_threading_currentthreadcputime{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "User time - {{app}} {{pod}} {{instance}}"
    },
    {}
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Garbage Collection Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{gc}} - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{gc}} - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "GC Throughput",
   "type": "stat",
   "description": "These calculations are experimental and need yet to be compared and validated against known correct results.",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}))-\n        sum(min(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "GC Throughput Evolution",
   "type": "timeseries",
   "description": "These calculations are experimental and need yet to be compared and validated against known correct results.  The way it is built does not work for multiple simultaneous JVMs, so accuracy requires selecting only one.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}))-\n        sum(min(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "GC Time (period)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__range]))",
     "legendFormat": "{{job}}-{{gc}} {{pod}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", area=\"heap\"}",
     "legendFormat": "{{area}}-max - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "{{area}}-committed - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "{{area}}-used - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_freephysicalmemorysize{instance=~\"$instance\"}",
     "legendFormat": "Total - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "java_lang_operatingsystem_totalphysicalmemorysize{instance=~\"$instance\"} - java_lang_operatingsystem_freephysicalmemorysize{instance=~\"$instance\"}",
     "legendFormat": "Used - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "{{area}}-committed - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\", instance=~\"$instance\"}",
     "legendFormat": "{{area}}-used - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Buffer Pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_capacity_bytes{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "{{pool}}-capacity - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_buffer_pool_used_bytes{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "{{pool}}-used - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  { "title": "Memory Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=~\".*Eden Space\", instance=~\"$instance\"}",
     "legendFormat": "Used - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=~\".*Eden Space\", instance=~\"$instance\"}",
     "legendFormat": "Committed - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=~\".*Old Gen.*\", instance=~\"$instance\"}",
     "legendFormat": "Used - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=~\".*Old Gen.*\", instance=~\"$instance\"}",
     "legendFormat": "Committed - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=~\".*Survivor Space\", instance=~\"$instance\"}",
     "legendFormat": "Used - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=~\".*Survivor Space\", instance=~\"$instance\"}",
     "legendFormat": "Committed - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"Metaspace\", instance=\"$instance\"}",
     "legendFormat": "Used - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=\"Metaspace\", instance=~\"$instance\"}",
     "legendFormat": "Committed - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"Compressed Class Space\", instance=~\"$instance\"}",
     "legendFormat": "Used - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=\"Compressed Class Space\", instance=~\"$instance\"}",
     "legendFormat": "Committed - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=~\".*CodeHeap.*\", instance=~\"$instance\"}",
     "legendFormat": "{{pool}} Used - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=~\".*CodeHeap.*\", instance=~\"$instance\"}",
     "legendFormat": "{{pool}} Committed - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Current Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Daemon Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_daemon{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Thread State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "{{state}} - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Runnable Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",state=\"RUNNABLE\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Waiting Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",state=~\"WAITING\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "New Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",state=\"NEW\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",state=\"BLOCKED\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  { "title": "Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Loaded Classes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Class Loading/Unloading",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 63 },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "Loaded - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_classes_unloaded_total{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "Unloaded - {{app}} {{pod}} {{instance}}"
    }
   ]
  }
 ]
}