/*-------------------------------------------------------------------------
 *
 * ora_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef ORA_KWLIST_D_H
#define ORA_KWLIST_D_H

#include "common/kwlookup.h"

static const char OraScanKeywords_kw_string[] =
	"abort\0"
	"absent\0"
	"absolute\0"
	"access\0"
	"accessible\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"array\0"
	"as\0"
	"asc\0"
	"asensitive\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"atomic\0"
	"attach\0"
	"attribute\0"
	"authid\0"
	"authorization\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"binary_double\0"
	"binary_double_infinity\0"
	"binary_double_nan\0"
	"binary_float\0"
	"binary_float_infinity\0"
	"binary_float_nan\0"
	"bit\0"
	"body\0"
	"boolean\0"
	"both\0"
	"breadth\0"
	"by\0"
	"byte\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compile\0"
	"compression\0"
	"concurrently\0"
	"conditional\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"date\0"
	"day\0"
	"deallocate\0"
	"debug\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"depends\0"
	"depth\0"
	"desc\0"
	"detach\0"
	"deterministic\0"
	"dictionary\0"
	"disable\0"
	"discard\0"
	"distinct\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"each\0"
	"editionable\0"
	"else\0"
	"empty\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"end\0"
	"enforced\0"
	"enum\0"
	"error\0"
	"escape\0"
	"event\0"
	"except\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"exec\0"
	"execute\0"
	"exists\0"
	"explain\0"
	"expression\0"
	"extend\0"
	"extension\0"
	"external\0"
	"false\0"
	"family\0"
	"fetch\0"
	"filter\0"
	"finalize\0"
	"first\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"format\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"hash\0"
	"having\0"
	"header\0"
	"hold\0"
	"hour\0"
	"identity\0"
	"if\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"indent\0"
	"index\0"
	"indexes\0"
	"infinite\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"ivysql\0"
	"join\0"
	"json\0"
	"json_array\0"
	"json_arrayagg\0"
	"json_exists\0"
	"json_object\0"
	"json_objectagg\0"
	"json_query\0"
	"json_scalar\0"
	"json_serialize\0"
	"json_table\0"
	"json_value\0"
	"keep\0"
	"key\0"
	"keys\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"level\0"
	"like\0"
	"limit\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"logged\0"
	"long\0"
	"loop\0"
	"mapping\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxvalue\0"
	"merge\0"
	"merge_action\0"
	"metadata\0"
	"method\0"
	"minute\0"
	"minvalue\0"
	"mode\0"
	"modify\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"nan\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"nested\0"
	"new\0"
	"next\0"
	"nfc\0"
	"nfd\0"
	"nfkc\0"
	"nfkd\0"
	"no\0"
	"nocache\0"
	"nocopy\0"
	"nocycle\0"
	"noextend\0"
	"nokeep\0"
	"nomaxvalue\0"
	"nominvalue\0"
	"none\0"
	"noneditionable\0"
	"noorder\0"
	"normalize\0"
	"normalized\0"
	"noscale\0"
	"noshard\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"number\0"
	"numeric\0"
	"nvl\0"
	"nvl2\0"
	"object\0"
	"objects\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"omit\0"
	"on\0"
	"only\0"
	"operator\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"package\0"
	"packages\0"
	"parallel\0"
	"parallel_enable\0"
	"parameter\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"passing\0"
	"password\0"
	"path\0"
	"pgextract\0"
	"pipelined\0"
	"placing\0"
	"plan\0"
	"plans\0"
	"policy\0"
	"polymorphic\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"program\0"
	"publication\0"
	"quote\0"
	"quotes\0"
	"range\0"
	"raw\0"
	"read\0"
	"real\0"
	"reassign\0"
	"recheck\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"reindex\0"
	"relative\0"
	"release\0"
	"relies_on\0"
	"rename\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"restart\0"
	"restrict\0"
	"result_cache\0"
	"return\0"
	"returning\0"
	"returns\0"
	"reuse\0"
	"revoke\0"
	"right\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"routine\0"
	"routines\0"
	"row\0"
	"rowid\0"
	"rows\0"
	"rowtype\0"
	"rule\0"
	"savepoint\0"
	"scalar\0"
	"scale\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"settings\0"
	"shard\0"
	"share\0"
	"sharing\0"
	"show\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"source\0"
	"specification\0"
	"sql\0"
	"sql_macro\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"string\0"
	"strip\0"
	"subscription\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysdate\0"
	"sysid\0"
	"system\0"
	"system_user\0"
	"systimestamp\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"target\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"text\0"
	"then\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"uescape\0"
	"unbounded\0"
	"uncommitted\0"
	"unconditional\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlogged\0"
	"until\0"
	"update\0"
	"updatexml\0"
	"user\0"
	"userenv\0"
	"using\0"
	"using_nls_comp\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"varchar2\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"virtual\0"
	"visible\0"
	"volatile\0"
	"when\0"
	"where\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"year\0"
	"yes\0"
	"zone";

static const uint16 OraScanKeywords_kw_offsets[] = {
	0,
	6,
	13,
	22,
	29,
	40,
	47,
	51,
	57,
	63,
	73,
	77,
	82,
	88,
	95,
	103,
	111,
	115,
	119,
	125,
	128,
	132,
	143,
	153,
	164,
	175,
	178,
	185,
	192,
	202,
	209,
	223,
	232,
	239,
	245,
	253,
	260,
	267,
	281,
	304,
	322,
	335,
	357,
	374,
	378,
	383,
	391,
	396,
	404,
	407,
	412,
	418,
	423,
	430,
	438,
	447,
	452,
	457,
	465,
	471,
	476,
	486,
	502,
	508,
	519,
	525,
	531,
	539,
	548,
	556,
	566,
	573,
	581,
	589,
	598,
	605,
	615,
	623,
	635,
	648,
	660,
	674,
	683,
	694,
	705,
	717,
	725,
	734,
	745,
	750,
	755,
	762,
	768,
	772,
	777,
	785,
	801,
	814,
	827,
	842,
	855,
	873,
	886,
	893,
	899,
	904,
	913,
	918,
	922,
	933,
	939,
	943,
	951,
	959,
	966,
	974,
	983,
	994,
	1003,
	1011,
	1018,
	1028,
	1039,
	1047,
	1053,
	1058,
	1065,
	1079,
	1090,
	1098,
	1106,
	1115,
	1118,
	1127,
	1134,
	1141,
	1146,
	1151,
	1163,
	1168,
	1174,
	1181,
	1190,
	1200,
	1204,
	1213,
	1218,
	1224,
	1231,
	1237,
	1244,
	1252,
	1262,
	1272,
	1277,
	1285,
	1292,
	1300,
	1311,
	1318,
	1328,
	1337,
	1343,
	1350,
	1356,
	1363,
	1372,
	1378,
	1384,
	1394,
	1398,
	1404,
	1412,
	1419,
	1427,
	1434,
	1439,
	1444,
	1453,
	1463,
	1473,
	1480,
	1486,
	1494,
	1503,
	1509,
	1518,
	1525,
	1533,
	1538,
	1545,
	1552,
	1557,
	1562,
	1571,
	1574,
	1580,
	1590,
	1600,
	1609,
	1616,
	1619,
	1627,
	1637,
	1647,
	1654,
	1660,
	1668,
	1677,
	1685,
	1694,
	1704,
	1711,
	1717,
	1723,
	1729,
	1741,
	1748,
	1756,
	1760,
	1768,
	1778,
	1787,
	1792,
	1802,
	1810,
	1813,
	1820,
	1830,
	1837,
	1842,
	1847,
	1858,
	1872,
	1884,
	1896,
	1911,
	1922,
	1934,
	1949,
	1960,
	1971,
	1976,
	1980,
	1985,
	1991,
	2000,
	2006,
	2011,
	2019,
	2027,
	2037,
	2043,
	2048,
	2054,
	2059,
	2065,
	2072,
	2077,
	2083,
	2093,
	2108,
	2117,
	2122,
	2129,
	2136,
	2141,
	2146,
	2154,
	2160,
	2168,
	2181,
	2190,
	2196,
	2209,
	2218,
	2225,
	2232,
	2241,
	2246,
	2253,
	2259,
	2264,
	2269,
	2275,
	2279,
	2288,
	2296,
	2302,
	2309,
	2313,
	2318,
	2322,
	2326,
	2331,
	2336,
	2339,
	2347,
	2354,
	2362,
	2371,
	2378,
	2389,
	2400,
	2405,
	2420,
	2428,
	2438,
	2449,
	2457,
	2465,
	2469,
	2477,
	2484,
	2492,
	2499,
	2504,
	2511,
	2517,
	2524,
	2532,
	2536,
	2541,
	2548,
	2556,
	2559,
	2563,
	2570,
	2575,
	2579,
	2584,
	2587,
	2592,
	2601,
	2608,
	2616,
	2619,
	2625,
	2636,
	2643,
	2647,
	2653,
	2658,
	2667,
	2675,
	2686,
	2692,
	2698,
	2706,
	2715,
	2724,
	2740,
	2750,
	2757,
	2765,
	2775,
	2783,
	2792,
	2797,
	2807,
	2817,
	2825,
	2830,
	2836,
	2843,
	2855,
	2864,
	2874,
	2884,
	2892,
	2901,
	2910,
	2918,
	2924,
	2935,
	2946,
	2956,
	2967,
	2975,
	2987,
	2993,
	3000,
	3006,
	3010,
	3015,
	3020,
	3029,
	3037,
	3047,
	3051,
	3062,
	3074,
	3082,
	3090,
	3099,
	3107,
	3117,
	3124,
	3135,
	3143,
	3151,
	3157,
	3165,
	3174,
	3187,
	3194,
	3204,
	3212,
	3218,
	3225,
	3231,
	3236,
	3245,
	3252,
	3260,
	3269,
	3273,
	3279,
	3284,
	3292,
	3297,
	3307,
	3314,
	3320,
	3327,
	3335,
	3342,
	3349,
	3356,
	3365,
	3372,
	3381,
	3391,
	3404,
	3411,
	3419,
	3432,
	3436,
	3442,
	3447,
	3456,
	3462,
	3468,
	3476,
	3481,
	3489,
	3496,
	3501,
	3510,
	3519,
	3524,
	3531,
	3545,
	3549,
	3559,
	3566,
	3577,
	3583,
	3593,
	3604,
	3610,
	3617,
	3625,
	3632,
	3639,
	3646,
	3652,
	3665,
	3675,
	3683,
	3693,
	3701,
	3707,
	3714,
	3726,
	3739,
	3745,
	3752,
	3764,
	3775,
	3782,
	3787,
	3796,
	3806,
	3811,
	3816,
	3821,
	3826,
	3836,
	3839,
	3848,
	3860,
	3870,
	3876,
	3884,
	3889,
	3894,
	3903,
	3911,
	3916,
	3922,
	3930,
	3940,
	3952,
	3966,
	3978,
	3984,
	3991,
	3999,
	4008,
	4017,
	4023,
	4030,
	4040,
	4045,
	4053,
	4059,
	4074,
	4081,
	4087,
	4096,
	4106,
	4112,
	4119,
	4127,
	4136,
	4145,
	4153,
	4161,
	4169,
	4174,
	4180,
	4188,
	4196,
	4205,
	4210,
	4216,
	4227,
	4234,
	4239,
	4246,
	4254,
	4259,
	4267,
	4273,
	4277,
	4291,
	4301,
	4312,
	4322,
	4332,
	4346,
	4355,
	4361,
	4369,
	4382,
	4391,
	4396,
	4400,
};

#define ORASCANKEYWORDS_NUM_KEYWORDS 559

static int
OraScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1119] = {
		29,    252,   32767, 201,   32767, 32767, 32767, 998,
		-32,   32767, 32767, 72,    32767, 271,   -13,   10,
		251,   32767, 347,   32767, 32767, 32767, -227,  32767,
		32767, 32767, 0,     32767, 32767, 32767, 556,   32767,
		32767, 32767, 32767, 1228,  -452,  32767, 0,     419,
		32767, 32767, 32767, -913,  675,   32767, 0,     32767,
		32767, 438,   32767, 32767, 449,   -822,  836,   32767,
		-68,   32767, 0,     415,   0,     255,   0,     629,
		0,     129,   32767, 32767, 0,     -200,  4,     376,
		-136,  44,    410,   477,   327,   305,   32767, 162,
		312,   32767, 0,     0,     32767, 32767, 516,   -273,
		32767, 32767, -98,   235,   278,   -178,  1021,  0,
		32767, 32767, 32767, 179,   230,   -101,  308,   32767,
		684,   244,   32767, 32767, 32767, 32767, 32767, 0,
		32767, 12,    0,     32767, 116,   226,   592,   32767,
		42,    32767, 32767, 0,     32767, 32767, -47,   138,
		32767, 170,   542,   32767, 32767, 0,     231,   32767,
		-9,    248,   32767, 32767, 392,   32767, 812,   230,
		214,   371,   890,   32767, 87,    35,    -53,   32767,
		0,     147,   83,    32767, 1166,  33,    32767, -376,
		32767, 0,     420,   32767, -312,  169,   0,     32767,
		32767, 334,   0,     174,   465,   32767, 534,   509,
		-834,  32767, 0,     32767, 65,    518,   32767, -734,
		-180,  -167,  1032,  293,   0,     -227,  32767, 1092,
		-590,  509,   -258,  32767, -285,  16,    638,   492,
		271,   32767, 898,   32767, 32767, 595,   397,   121,
		32767, 84,    -486,  139,   669,   32767, 197,   32767,
		400,   258,   208,   0,     0,     0,     32767, -930,
		32767, 32767, 32767, 471,   -16,   32767, 0,     165,
		32767, 217,   32767, 315,   0,     32767, 32767, 232,
		32767, 32767, 435,   32767, -46,   219,   271,   32767,
		519,   32767, 32767, 0,     82,    42,    32767, 32767,
		213,   378,   258,   32767, 0,     106,   -81,   -310,
		32767, 382,   196,   32767, 32767, 32767, 32767, 32767,
		32767, 743,   0,     32767, 32767, 0,     32767, 580,
		0,     32767, -383,  32767, 70,    32767, 47,    374,
		32767, 187,   -411,  32767, -237,  124,   32767, 32767,
		32767, 0,     57,    -178,  -150,  61,    32767, 32767,
		32767, 32767, 32767, -365,  32767, 0,     32767, 32767,
		32767, 32767, 32767, -36,   205,   32767, 289,   0,
		528,   32767, 32767, 32767, 511,   32767, 639,   32767,
		32767, 32767, -418,  132,   -294,  173,   -78,   32767,
		32767, 124,   -757,  32767, 32767, -275,  32767, 32767,
		32767, 32767, 464,   32767, 194,   -474,  25,    448,
		102,   84,    164,   -130,  60,    117,   0,     32767,
		439,   0,     0,     32767, 151,   423,   450,   349,
		0,     -92,   32767, 32767, 32767, -632,  0,     345,
		32767, 32767, 86,    0,     32767, 76,    32767, 32767,
		32767, -83,   32767, 32767, 548,   806,   32767, 481,
		454,   453,   32767, -306,  144,   81,    956,   283,
		32767, 0,     46,    32767, 32767, 277,   607,   32767,
		-43,   32767, 0,     32767, 434,   32767, 32767, 162,
		32767, 289,   -1096, -168,  -683,  0,     32767, -35,
		28,    303,   354,   -454,  469,   442,   315,   32767,
		0,     32767, 32767, 0,     32767, 0,     816,   -339,
		32767, 32767, 7,     32767, -501,  446,   32767, 32767,
		-260,  32767, 32767, 0,     32767, 68,    -632,  472,
		925,   0,     32767, 32767, -361,  54,    32767, -955,
		0,     32767, 32767, 1270,  -208,  32767, 0,     1317,
		32767, 32767, 322,   32767, 32767, 458,   579,   374,
		32767, 0,     314,   393,   32767, 358,   32767, -167,
		-628,  122,   32767, 0,     233,   -479,  -1065, 0,
		32767, 32767, 407,   1141,  332,   0,     32767, -209,
		333,   32767, 415,   32767, 0,     0,     460,   0,
		686,   32767, 0,     32767, 207,   32767, 632,   32767,
		0,     0,     356,   -42,   677,   32767, 233,   0,
		32767, 131,   21,    406,   1056,  32767, -137,  510,
		32767, 0,     1,     32767, 118,   740,   32767, 0,
		32767, 183,   182,   0,     32767, 32767, 32767, 32767,
		365,   128,   -106,  32767, 440,   441,   32767, 714,
		524,   32767, 32767, 0,     0,     1124,  32767, 32767,
		32767, 32767, 243,   32767, 378,   32767, 303,   144,
		32767, 52,    830,   32767, 647,   23,    135,   908,
		280,   19,    309,   142,   32767, 74,    -241,  259,
		156,   32767, -614,  72,    652,   32767, 32767, 37,
		32767, 32767, 383,   458,   32767, 202,   32767, 32767,
		404,   503,   32767, 32767, 396,   401,   32767, 32767,
		0,     32767, 14,    0,     -16,   0,     37,    164,
		32767, 71,    32767, 535,   182,   0,     -132,  0,
		32767, 0,     0,     32767, 32767, 959,   207,   32767,
		268,   55,    32767, -363,  464,   32767, 252,   -904,
		0,     1075,  32767, -141,  505,   470,   -708,  0,
		-131,  777,   32767, 32767, 32767, 364,   588,   628,
		32767, 0,     -303,  50,    0,     294,   32767, 32767,
		383,   -70,   391,   135,   32767, 274,   0,     32767,
		224,   32767, 147,   502,   32767, 32767, 13,    32767,
		122,   390,   113,   -3,    32767, 0,     403,   32767,
		309,   32767, 0,     0,     493,   32767, 527,   32767,
		32767, 32767, -189,  32767, 46,    133,   0,     328,
		263,   358,   32767, 32767, 32767, 32767, -534,  281,
		52,    334,   32767, 32767, -171,  -217,  32767, 183,
		32767, 0,     -735,  52,    0,     0,     0,     34,
		32767, 32767, 439,   0,     -26,   286,   32767, -56,
		425,   32767, 32767, 32767, 200,   32767, 32767, 328,
		0,     164,   0,     146,   0,     -999,  980,   32767,
		32767, 491,   298,   98,    311,   235,   86,    32767,
		217,   0,     99,    0,     32767, 165,   32767, 32767,
		-467,  32767, 493,   0,     0,     32767, 156,   148,
		1294,  41,    -24,   93,    32767, 118,   -14,   0,
		468,   32767, 195,   0,     462,   465,   499,   1367,
		861,   32767, 0,     103,   32767, 77,    32767, -373,
		235,   -130,  273,   46,    32767, 490,   32767, 32767,
		-89,   32767, 32767, 32767, 32767, 32767, 333,   -258,
		0,     213,   428,   32767, -334,  463,   444,   32767,
		32767, 395,   421,   32767, 76,    171,   32767, 32767,
		689,   24,    339,   32767, 0,     550,   0,     371,
		1433,  -765,  32767, 32767, 1094,  204,   32767, 176,
		503,   256,   781,   -282,  0,     -434,  0,     344,
		-341,  0,     32767, 0,     0,     -860,  32767, 110,
		81,    495,   32767, 545,   32767, 32767, 0,     43,
		-91,   -671,  404,   32767, -335,  479,   506,   355,
		-62,   463,   206,   0,     32767, 240,   17,    0,
		32767, 32767, 32767, 32767, 5,     32767, 32767, 221,
		32767, 32767, 69,    32767, 32767, -460,  30,    32767,
		32767, 107,   32767, 0,     256,   161,   0,     45,
		32767, -342,  0,     229,   0,     313,   126,   32767,
		32767, 301,   80,    0,     32767, 0,     56,    32767,
		33,    -65,   32767, 32767, 0,     32767, 0,     -594,
		187,   0,     -130,  0,     32767, 32767, 80,    32767,
		0,     32767, 0,     -202,  148,   32767, 372,   32767,
		65,    473,   555,   9,     32767, 32767, 484,   -385,
		32767, 0,     32767, 32767, 32767, -279,  0,     32767,
		99,    0,     -35,   32767, 0,     32767, 261,   41,
		32767, 143,   177,   196,   32767, 408,   0,     0,
		32767, 418,   107,   0,     0,     266,   -274,  485,
		123,   32767, 0,     0,     0,     0,     447,   32767,
		32767, 0,     633,   32767, 32767, -470,  154,   -80,
		32767, 32767, 32767, 36,    32767, 187,   241,   32767,
		32767, 0,     0,     32767, -334,  -794,  32767, 32767,
		-20,   32767, 552,   0,     379,   212,   924,   140,
		90,    0,     32767, 32767, 282,   32767, 32767, 712,
		125,   -57,   32767, 0,     88,    32767, 0,     314,
		336,   32767, 0,     201,   246,   32767, 0,     320,
		32767, 112,   0,     32767, 180,   0,     32767, 389,
		32767, 32767, 32767, 0,     451,   32767, 0,     32767,
		32767, 275,   42,    -585,  32767, 203,   32767, 51,
		286,   -648,  32767, 32767, 359,   32767, 91,    73,
		32767, 32767, 0,     2,     0,     0,     0,     0,
		32767, 855,   20,    240,   0,     0,     0,     63,
		317,   67,    11,    0,     32767, 32767, 74
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 0;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 31 + c;
	}
	return h[a % 1119] + h[b % 1119];
}

const ScanKeywordList OraScanKeywords = {
	OraScanKeywords_kw_string,
	OraScanKeywords_kw_offsets,
	OraScanKeywords_hash_func,
	ORASCANKEYWORDS_NUM_KEYWORDS,
	22
};

#endif							/* ORA_KWLIST_D_H */
